# Generated by Django 3.0.7 on 2023-09-10 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_001', '0012_auto_20230701_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='address',
            field=models.TextField(max_length=250),
        ),
    ]
